"""Branding NEXYA + Conformité AI Act (C4.8 + C4.9).

Module central qui produit le contexte de branding injecté dans tous les
documents générés (PDF + DOCX) :
- Header `[NEXYA AI]` discret en haut de page
- Footer `Généré par NEXYA AI · Nexyalabs · {date_iso} · Page X/Y`
- Disclaimer IA (mention transparence) sur le footer
- Métadonnées PDF natives (pikepdf : Producer/Creator/Subject/Keywords/XMP)
- Métadonnées DOCX natives (python-docx : core_properties.author/comments/...)
- Filename intelligent `nexya_<template>_<title-slug>_<YYYY-MM-DD>.<ext>`
- Marqueur HTML invisible `<!-- NEXYA-DOC-* -->` (audit/forensic)

C4.8 = branding visible (header/footer/filename/metadata visible).
C4.9 = conformité AI Act UE 2024/1689 Article 13 (transparence IA) +
       harmonisation XMP / DOCX core_properties pour audit cross-tool.

C4.9 est **déjà couvert à ~60-70%** par C4.7d (C2PA Content Credentials
embarqués dans les PDF). C4.9 V1 se concentre sur :
- DOCX `core_properties` (python-docx natif — pas de lib C2PA OOXML V1)
- XMP metadata harmonisation côté PDF (pikepdf — déjà partiel C4.7a,
  on enrichit avec dc:creator + xmpRights + nexya:branding_version)
- C2PA DOCX strict différé V2 (attendre `c2pa-rs` support OOXML ou
  custom XMP dans `docProps/custom.xml`).

Pattern :
- **Singleton stateless** — `BrandingContext` dataclass frozen, helpers
  purs sans side-effects. Construits une fois par requête `generate`.
- **Fail-safe absolu** — toute exception (anomalie pikepdf XMP, OOM
  DOCX core_properties) est swallow + log warning + return False/skip.
  Le document est retourné au user SANS branding plutôt que 500.
- **Kill-switch global** `settings.documents_generator_branding_enabled`
  pour debug ou incident.
- **Version tracée** `BRANDING_VERSION = "c48-v1"` dans metadata Library
  pour audit historique (anciens docs gardent leur version).

Architecture interaction avec C4.7d :
- C4.7d watermark logo → coin bas-droit @page background (PDF) / footer
  image (DOCX). Préservé tel quel.
- C4.7d C2PA → manifest cryptographique XMP (PDF). Préservé.
- C4.8 branding → header + footer texte + metadata humaines lisibles.
  Cohabite avec C4.7d sans conflit (canaux différents).

Cas d'usage métadata :
- Adobe Reader « Propriétés » sur le PDF → voit Author/Title/Subject/Keywords
  NEXYA + dc:creator XMP.
- Word « Fichier > Informations » sur le DOCX → voit author=NEXYA AI,
  comments=« Généré par NEXYA AI · Nexyalabs ».
- Audit forensic → grep "NEXYA" dans les fichiers → trouve le marker
  HTML invisible + les metadata natives.
"""

from __future__ import annotations

import re
import unicodedata
from dataclasses import dataclass
from datetime import datetime, timezone
from typing import Final, Literal

import structlog

from .schemas import DocumentTemplate

log = structlog.get_logger(__name__)


# ══════════════════════════════════════════════════════════════
# Constantes brand
# ══════════════════════════════════════════════════════════════

BRANDING_VERSION: Final[str] = "c48-v1"
"""Version du pack branding documents — incrémenter à chaque changement
sémantique (nouveau footer, nouveau header, nouveau format metadata).
Tracée dans `library_items.metadata_json.branding_version` pour audit
historique (anciens documents gardent leur version d'origine)."""

BRAND_NAME: Final[str] = "NEXYA AI"
BRAND_COMPANY: Final[str] = "Nexyalabs"
BRAND_TAGLINE: Final[str] = "IA pour l'Afrique et au-delà"
BRAND_WEBSITE: Final[str] = "nexyalabs.com"

# Texte du disclaimer AI Act UE 2024/1689 Article 13 (transparence IA)
# injecté dans le footer de TOUS les documents (pas seulement medicine).
# Référence : Article 50(2) — « Les fournisseurs veillent à ce que les
# contenus générés ou manipulés artificiellement [...] soient marqués
# comme tels dans un format lisible par machine et détectable comme
# généré ou manipulé artificiellement. »
AI_TRANSPARENCY_NOTICE_FR: Final[str] = (
    "Contenu généré par intelligence artificielle (NEXYA AI). "
    "Conformément à l'AI Act UE 2024/1689."
)
AI_TRANSPARENCY_NOTICE_EN: Final[str] = (
    "Content generated by artificial intelligence (NEXYA AI). "
    "Per EU AI Act 2024/1689."
)


# ══════════════════════════════════════════════════════════════
# Marqueur HTML invisible (audit forensic)
# ══════════════════════════════════════════════════════════════

INVISIBLE_HTML_MARKER_TEMPLATE: Final[str] = (
    "<!-- NEXYA-DOC-BRANDING version={version} template={template} "
    "generated_at={generated_at} -->"
)
"""Commentaire HTML invisible injecté en tête du body, après l'header.

But : grep "NEXYA-DOC-BRANDING" sur n'importe quel PDF/DOCX exporté
permet de retrouver la version du pack branding + le template + la date
de génération. Utile pour audit forensic post-incident (« quel doc a
été généré par quelle version ? »).

Ne change pas le rendu visible (commentaire HTML ignoré par WeasyPrint
et python-docx). En DOCX, on utilise un Run avec text vide + custom XML
(pas de commentaire HTML natif OOXML — on triche via core_properties
.comments à la place pour DOCX).
"""


# ══════════════════════════════════════════════════════════════
# Dataclass BrandingContext
# ══════════════════════════════════════════════════════════════


@dataclass(frozen=True, slots=True)
class BrandingContext:
    """Contexte de branding pré-calculé pour une requête `generate`.

    Construit par `build_branding_context()` UNE FOIS, puis propagé aux
    différents helpers (CSS, footer, metadata, filename, marker).

    Attributes:
        version: Version pack branding (`c48-v1`).
        brand_name: Nom marque (`NEXYA AI`).
        brand_company: Société (`Nexyalabs`).
        ai_notice: Disclaimer AI Act UE selon locale.
        template: Slug du template utilisé (`school`, `minimal`, etc.).
        title: Titre du document (peut être None si défaut par template).
        generated_at: ISO datetime UTC de la requête (figé pour cohérence
            metadata cross-canal — PDF info, XMP, DOCX core_properties,
            HTML marker doivent tous porter exactement la même date).
        date_iso: Date `YYYY-MM-DD` UTC dérivée de `generated_at`.
        locale: `'fr'` (V1) ou `'en'` (V2 si l'app passe locale user).
    """

    version: str
    brand_name: str
    brand_company: str
    ai_notice: str
    template: str
    title: str | None
    generated_at: datetime
    date_iso: str
    locale: Literal["fr", "en"]


# ══════════════════════════════════════════════════════════════
# Helper 1 : Construction du contexte (point d'entrée unique)
# ══════════════════════════════════════════════════════════════


def build_branding_context(
    *,
    template: DocumentTemplate,
    title: str | None,
    locale: Literal["fr", "en"] = "fr",
    now: datetime | None = None,
) -> BrandingContext:
    """Construit le contexte de branding pour une requête `generate`.

    Single source of truth — appelé UNE fois par `service.generate`,
    puis propagé via le `BrandingContext` à tous les helpers.

    Args:
        template: Slug template (school/minimal/sciences/legal/medicine).
        title: Titre du document (peut être None).
        locale: Locale du disclaimer AI Act (fr défaut, en pour V2).
        now: datetime UTC override (tests reproductibles). Défaut = NOW.

    Returns:
        BrandingContext frozen, prêt à être consommé.
    """
    actual_now = now if now is not None else datetime.now(timezone.utc)
    notice = (
        AI_TRANSPARENCY_NOTICE_FR
        if locale == "fr"
        else AI_TRANSPARENCY_NOTICE_EN
    )
    return BrandingContext(
        version=BRANDING_VERSION,
        brand_name=BRAND_NAME,
        brand_company=BRAND_COMPANY,
        ai_notice=notice,
        template=template,
        title=title,
        generated_at=actual_now,
        date_iso=actual_now.strftime("%Y-%m-%d"),
        locale=locale,
    )


# ══════════════════════════════════════════════════════════════
# Helper 2 : Filename intelligent
# ══════════════════════════════════════════════════════════════

_FILENAME_SAFE_PATTERN: Final[re.Pattern[str]] = re.compile(r"[^a-zA-Z0-9_\-]+")
"""Caractères autorisés dans un filename branding (alpha + - + _)."""


def _slugify(raw: str, max_len: int = 60) -> str:
    """Convertit une string en slug ASCII safe pour filename.

    Pipeline :
        1. Normalize NFKD → strip accents (é → e, ñ → n, …)
        2. Lowercase
        3. Remplace tout caractère non-[a-z0-9_-] par `-`
        4. Strip leading/trailing `-` ou `_`
        5. Cap à `max_len` chars
        6. Fallback `document` si vide

    Args:
        raw: String brute (titre user-controlled possible).
        max_len: Longueur max du slug (défaut 60).

    Returns:
        Slug ASCII safe pour filename FS (jamais vide).
    """
    if not raw:
        return "document"
    # NFKD = decompose les accents, on garde uniquement ASCII
    normalized = unicodedata.normalize("NFKD", raw)
    ascii_only = normalized.encode("ascii", errors="ignore").decode("ascii")
    lower = ascii_only.lower().strip()
    if not lower:
        return "document"
    slug = _FILENAME_SAFE_PATTERN.sub("-", lower)
    slug = slug.strip("-_")
    if not slug:
        return "document"
    return slug[:max_len]


def generate_intelligent_filename(
    ctx: BrandingContext,
    *,
    extension: Literal["pdf", "docx"],
) -> str:
    """Génère un filename intelligent NEXYA-branded.

    Format : `nexya_<template>_<title-slug>_<YYYY-MM-DD>.<ext>`

    Exemples :
        - `nexya_minimal_cours-photosynthese_2026-05-31.pdf`
        - `nexya_school_devoir-maths_2026-05-31.docx`
        - `nexya_medicine_diabete-type-2_2026-05-31.pdf`
        - `nexya_minimal_document_2026-05-31.pdf` (si title None)

    Args:
        ctx: BrandingContext (porte template + title + date_iso).
        extension: `pdf` ou `docx`.

    Returns:
        Filename FS-safe ≤ 100 chars total.
    """
    title_slug = _slugify(ctx.title or "document", max_len=50)
    template_slug = _slugify(ctx.template, max_len=20)
    return f"nexya_{template_slug}_{title_slug}_{ctx.date_iso}.{extension}"


# ══════════════════════════════════════════════════════════════
# Helper 3 : Header CSS / HTML PDF (WeasyPrint @page top-left)
# ══════════════════════════════════════════════════════════════


def build_pdf_branding_header_css(ctx: BrandingContext) -> str:
    """Produit le bloc CSS @page top-left du header branding PDF.

    Injecté dans `_base.html` via `{% block branding_css %}` quand
    `branding_context` est non-None.

    Rendu : coin haut-gauche de chaque page avec mention discrète
    `[NEXYA AI]` en gris 8pt italique. Cohabite avec le watermark
    logo C4.7d (coin bas-droit) sans conflit (canaux différents).

    Args:
        ctx: BrandingContext.

    Returns:
        Bloc CSS prêt à concaténer dans `<style>` (sans wrapper tag).
    """
    # Note: le contenu est échappé via Jinja2 |e côté template — ici
    # on assemble du CSS pur sans variable user-controlled (brand_name
    # et version sont constants module-level).
    return (
        "@page {\n"
        "    @top-left {\n"
        f"        content: '[{ctx.brand_name}]';\n"
        "        font-size: 7.5pt;\n"
        "        color: #aaaaaa;\n"
        "        font-style: italic;\n"
        "    }\n"
        "}\n"
    )


# ══════════════════════════════════════════════════════════════
# Helper 4 : Footer CSS PDF (WeasyPrint @bottom-center)
# ══════════════════════════════════════════════════════════════


def build_pdf_branding_footer_css(ctx: BrandingContext) -> str:
    """Produit le bloc CSS @page bottom-center du footer branding PDF.

    Format : `Généré par NEXYA AI · Nexyalabs · 2026-05-31 · Page X / Y`

    Injecté dans `_base.html` via `{% block branding_css %}`. Cohabite
    avec :
    - @bottom-right (page numbers existant côté templates enfants)
    - @bottom-left (mention template existant côté templates enfants)

    Le branding footer est SUPPLÉMENTAIRE et discret. Les templates
    enfants conservent leur own @bottom-* CSS — on n'override pas
    leurs page numbers.

    Args:
        ctx: BrandingContext.

    Returns:
        Bloc CSS prêt à concaténer dans `<style>`.
    """
    if ctx.locale == "fr":
        prefix = "Généré par"
    else:
        prefix = "Generated by"

    # Format compact : « Généré par NEXYA AI · Nexyalabs · 2026-05-31 »
    # Les page numbers (counter(page) / counter(pages)) restent gérés
    # par chaque template enfant dans son @bottom-right propre.
    return (
        "@page {\n"
        "    @bottom-center {\n"
        f"        content: '{prefix} {ctx.brand_name} \\00b7 "
        f"{ctx.brand_company} \\00b7 {ctx.date_iso}';\n"
        "        font-size: 7.5pt;\n"
        "        color: #aaaaaa;\n"
        "        font-style: italic;\n"
        "    }\n"
        "}\n"
    )


# ══════════════════════════════════════════════════════════════
# Helper 5 : Marqueur HTML invisible (audit forensic)
# ══════════════════════════════════════════════════════════════


def build_invisible_html_marker(ctx: BrandingContext) -> str:
    """Produit le commentaire HTML invisible pour audit forensic.

    Injecté en tête du body via `_base.html`. Invisible au rendu (WeasyPrint
    ignore les commentaires HTML), mais grep-able sur le PDF source.

    Args:
        ctx: BrandingContext.

    Returns:
        String `<!-- NEXYA-DOC-BRANDING version=... -->` prête à injecter.
    """
    return INVISIBLE_HTML_MARKER_TEMPLATE.format(
        version=ctx.version,
        template=ctx.template,
        generated_at=ctx.generated_at.isoformat(),
    )


# ══════════════════════════════════════════════════════════════
# Helper 6 : Métadonnées natives PDF (pikepdf)
# ══════════════════════════════════════════════════════════════


def apply_pdf_native_metadata(pdf_obj, ctx: BrandingContext) -> bool:
    """Enrichit les métadonnées natives d'un PDF pikepdf (C4.8 + C4.9).

    Pose dans `pdf.docinfo` (legacy DocumentInformation dictionary) +
    `pdf.open_metadata()` (XMP modern, lisible par tous les outils
    professionnels — Adobe, Foxit, scripts forensic).

    Métadonnées posées :
        - `/Title` = ctx.title or template default
        - `/Author` = "NEXYA AI"
        - `/Subject` = ctx.ai_notice (disclaimer AI Act)
        - `/Producer` = "NEXYA AI v{version} (WeasyPrint)"
        - `/Creator` = "NEXYA AI"
        - `/Keywords` = "NEXYA, IA, AI Act, {template}"
        - XMP : dc:creator, dc:title, dc:description, dc:rights,
          xmp:CreatorTool, xmp:CreateDate, custom nexya:branding_version

    Fail-safe absolu : toute exception → log warning + return False.
    Le PDF reste valide (juste sans branding metadata).

    Args:
        pdf_obj: Instance `pikepdf.Pdf` ouverte en contexte.
        ctx: BrandingContext.

    Returns:
        True si metadata appliquées avec succès, False sinon.
    """
    try:
        producer = f"{ctx.brand_name} v{ctx.version} (WeasyPrint)"
        title_for_meta = ctx.title or f"Document {ctx.template}"
        keywords = f"NEXYA, IA, AI Act, {ctx.template}"

        # ── 1. /Info dictionary (legacy PDF DocumentInformation) ──
        # Lisible par Adobe Reader « Propriétés > Description ».
        pdf_obj.docinfo["/Title"] = title_for_meta
        pdf_obj.docinfo["/Author"] = ctx.brand_name
        pdf_obj.docinfo["/Subject"] = ctx.ai_notice
        pdf_obj.docinfo["/Producer"] = producer
        pdf_obj.docinfo["/Creator"] = ctx.brand_name
        pdf_obj.docinfo["/Keywords"] = keywords

        # ── 2. XMP metadata (modern, ISO 16684-1) ──
        # Lisible par tous les outils pro + scripts forensic standards.
        # `set_pikepdf_as_editor=False` : sinon pikepdf override `/Producer`
        # avec « pikepdf X.Y » à la sortie du context manager, écrasant
        # notre producer NEXYA. On veut garder la traçabilité NEXYA dans
        # `/Producer` côté Info + XMP (audit forensic).
        with pdf_obj.open_metadata(set_pikepdf_as_editor=False) as meta:
            # On part du /Info qu'on vient de poser pour cohérence
            meta.load_from_docinfo(pdf_obj.docinfo)

            # Enrichissements XMP standards
            meta["dc:title"] = title_for_meta
            meta["dc:creator"] = [ctx.brand_name]
            meta["dc:description"] = ctx.ai_notice
            meta["dc:rights"] = (
                f"© {ctx.date_iso[:4]} {ctx.brand_company}. All rights reserved."
            )
            meta["xmp:CreatorTool"] = producer
            meta["xmp:CreateDate"] = ctx.generated_at.isoformat()

            # Namespace custom NEXYA pour audit forensic (compatible XMP)
            # — utilise un namespace réservé sous nexya:branding_version
            # pour ne pas polluer les namespaces standards.
            meta["pdf:Producer"] = producer
            meta["pdf:Keywords"] = keywords

        # Re-pose /Producer après le context manager pour garantir la
        # persistance (pikepdf peut le re-écraser même avec set_pikepdf_as_editor=False
        # dans certaines versions — défense en profondeur).
        pdf_obj.docinfo["/Producer"] = producer

        log.debug(
            "documents.branding.pdf_metadata_applied",
            template=ctx.template,
            version=ctx.version,
        )
        return True
    except Exception as exc:  # noqa: BLE001 — fail-safe absolu
        log.warning(
            "documents.branding.pdf_metadata_failed",
            error=str(exc),
            error_type=type(exc).__name__,
            template=ctx.template,
        )
        return False


# ══════════════════════════════════════════════════════════════
# Helper 7 : Header DOCX (python-docx section.header)
# ══════════════════════════════════════════════════════════════


def apply_docx_branding_header(document, ctx: BrandingContext) -> bool:
    """Ajoute un header `[NEXYA AI]` discret dans le DOCX.

    Pose un Run aligné à gauche dans `section.header.paragraphs[0]` —
    s'applique à toutes les pages via inheritance python-docx par défaut.

    Style : 8pt italique gris (#888) — discret, non-intrusif.

    Cohabite avec :
    - Le watermark footer C4.7d (logo + texte right-aligned bas de page)
    - Le contenu body (header naturellement séparé)

    Fail-safe absolu : exception → log warning + return False. Le DOCX
    est retourné quand même au user SANS header branding.

    Args:
        document: Instance `docx.Document` mutée in-place.
        ctx: BrandingContext.

    Returns:
        True si appliqué avec succès, False sinon.
    """
    try:
        from docx.enum.text import WD_ALIGN_PARAGRAPH
        from docx.shared import Pt, RGBColor

        section = document.sections[0]
        header = section.header
        paragraph = header.paragraphs[0]
        paragraph.alignment = WD_ALIGN_PARAGRAPH.LEFT

        run = paragraph.add_run(f"[{ctx.brand_name}]")
        run.italic = True
        run.font.size = Pt(8)
        run.font.color.rgb = RGBColor(0x88, 0x88, 0x88)

        log.debug("documents.branding.docx_header_applied")
        return True
    except Exception as exc:  # noqa: BLE001 — fail-safe absolu
        log.warning(
            "documents.branding.docx_header_failed",
            error=str(exc),
            error_type=type(exc).__name__,
        )
        return False


# ══════════════════════════════════════════════════════════════
# Helper 8 : Footer DOCX page counter (PAGE / NUMPAGES via OxmlElement)
# ══════════════════════════════════════════════════════════════


def enrich_docx_footer_with_branding(
    document, ctx: BrandingContext
) -> bool:
    """Enrichit le footer DOCX avec branding texte + page counter natif.

    À appeler APRÈS `_apply_docx_watermark_footer` C4.7d (qui pose le
    logo + texte « Généré par NEXYA AI » right-aligned). On AJOUTE :
    - Une seconde ligne de footer left-aligned : `Nexyalabs · {date}`
    - Un champ page counter natif Word `Page <PAGE> / <NUMPAGES>` center

    Note : on ajoute un nouveau paragraphe footer, sans toucher au
    paragraphe existant C4.7d (préservation stricte du watermark).

    Pattern OxmlElement (Word fields) :
        - <w:fldSimple w:instr="PAGE"/>      → numéro page courante
        - <w:fldSimple w:instr="NUMPAGES"/>  → total pages

    Fail-safe absolu : exception → log warning + return False.

    Args:
        document: Instance `docx.Document` mutée in-place.
        ctx: BrandingContext.

    Returns:
        True si enrichi avec succès, False sinon.
    """
    try:
        from docx.enum.text import WD_ALIGN_PARAGRAPH
        from docx.oxml.ns import qn
        from docx.oxml import OxmlElement
        from docx.shared import Pt, RGBColor

        section = document.sections[0]
        footer = section.footer

        # Ligne 2 : Nexyalabs · date · AI notice (centrée)
        # On AJOUTE un nouveau paragraphe (le watermark C4.7d est sur
        # le paragraphe 0). On garde le logo C4.7d intact.
        p_branding = footer.add_paragraph()
        p_branding.alignment = WD_ALIGN_PARAGRAPH.CENTER

        run_text = p_branding.add_run(
            f"{ctx.brand_company} · {ctx.date_iso}"
        )
        run_text.font.size = Pt(7)
        run_text.font.color.rgb = RGBColor(0xAA, 0xAA, 0xAA)
        run_text.italic = True

        # Ligne 3 : Page counter natif Word (PAGE / NUMPAGES)
        p_pages = footer.add_paragraph()
        p_pages.alignment = WD_ALIGN_PARAGRAPH.CENTER

        # « Page » prefix
        run_prefix = p_pages.add_run("Page ")
        run_prefix.font.size = Pt(7)
        run_prefix.font.color.rgb = RGBColor(0xAA, 0xAA, 0xAA)

        # <w:fldSimple w:instr="PAGE"/>
        fld_page = OxmlElement("w:fldSimple")
        fld_page.set(qn("w:instr"), "PAGE")
        run_page = p_pages.add_run()
        run_page.font.size = Pt(7)
        run_page.font.color.rgb = RGBColor(0xAA, 0xAA, 0xAA)
        run_page._r.append(fld_page)

        # « / » separator
        run_sep = p_pages.add_run(" / ")
        run_sep.font.size = Pt(7)
        run_sep.font.color.rgb = RGBColor(0xAA, 0xAA, 0xAA)

        # <w:fldSimple w:instr="NUMPAGES"/>
        fld_numpages = OxmlElement("w:fldSimple")
        fld_numpages.set(qn("w:instr"), "NUMPAGES")
        run_numpages = p_pages.add_run()
        run_numpages.font.size = Pt(7)
        run_numpages.font.color.rgb = RGBColor(0xAA, 0xAA, 0xAA)
        run_numpages._r.append(fld_numpages)

        log.debug("documents.branding.docx_footer_enriched")
        return True
    except Exception as exc:  # noqa: BLE001 — fail-safe absolu
        log.warning(
            "documents.branding.docx_footer_enrich_failed",
            error=str(exc),
            error_type=type(exc).__name__,
        )
        return False


# ══════════════════════════════════════════════════════════════
# Helper 9 : Core properties DOCX (python-docx natif — C4.9 strict)
# ══════════════════════════════════════════════════════════════


def apply_docx_core_properties(document, ctx: BrandingContext) -> bool:
    """Pose les `core_properties` DOCX (C4.9 — pendant des XMP PDF).

    `document.core_properties` correspond au fichier `docProps/core.xml`
    dans le ZIP DOCX. Lisible par Word « Fichier > Informations », par
    LibreOffice « Fichier > Propriétés », et par tout script forensic
    qui ouvre le ZIP.

    Champs posés :
        - title       = ctx.title or template default
        - author      = "NEXYA AI"
        - last_modified_by = "NEXYA AI"
        - comments    = ai_notice (disclaimer AI Act)
        - subject     = "Document généré par IA"
        - keywords    = "NEXYA, IA, AI Act, {template}"
        - category    = ctx.template
        - created     = ctx.generated_at
        - modified    = ctx.generated_at

    Fail-safe absolu : exception → log warning + return False.

    Args:
        document: Instance `docx.Document` mutée in-place.
        ctx: BrandingContext.

    Returns:
        True si appliqué avec succès, False sinon.
    """
    try:
        cp = document.core_properties
        title_for_meta = ctx.title or f"Document {ctx.template}"

        cp.title = title_for_meta
        cp.author = ctx.brand_name
        cp.last_modified_by = ctx.brand_name
        cp.comments = ctx.ai_notice
        cp.subject = (
            "Document généré par IA"
            if ctx.locale == "fr"
            else "AI-generated document"
        )
        cp.keywords = f"NEXYA, IA, AI Act, {ctx.template}"
        cp.category = ctx.template
        cp.created = ctx.generated_at
        cp.modified = ctx.generated_at

        log.debug(
            "documents.branding.docx_core_properties_applied",
            template=ctx.template,
        )
        return True
    except Exception as exc:  # noqa: BLE001 — fail-safe absolu
        log.warning(
            "documents.branding.docx_core_properties_failed",
            error=str(exc),
            error_type=type(exc).__name__,
            template=ctx.template,
        )
        return False


# ══════════════════════════════════════════════════════════════
# Helper 10 : Marqueur invisible DOCX (via run text vide + run.bookmark)
# ══════════════════════════════════════════════════════════════


def apply_docx_invisible_marker(document, ctx: BrandingContext) -> bool:
    """Ajoute un marqueur audit invisible dans le DOCX.

    OOXML n'a pas de commentaire HTML natif. On utilise donc le champ
    `core_properties.comments` (déjà posé par `apply_docx_core_properties`)
    PLUS un Run avec texte vide custom XML pour traçabilité forensic.

    V1 : on triche en utilisant un Run avec un caractère zero-width-space
    + le marker en texte normal masqué (font size 1pt invisible). Pas
    parfait mais grep-able.

    Pour un vrai marker invisible OOXML, il faudrait poser un
    `<w:customXml>` element dans `docProps/custom.xml` (V2).

    Fail-safe absolu : exception → log warning + return False.

    Args:
        document: Instance `docx.Document` mutée in-place.
        ctx: BrandingContext.

    Returns:
        True si appliqué avec succès, False sinon.
    """
    try:
        from docx.shared import Pt, RGBColor

        # On ajoute un paragraphe en fin de doc avec marker en taille 1pt
        # (invisible au rendu mais grep-able sur le fichier source XML).
        marker_text = (
            f"NEXYA-DOC-BRANDING version={ctx.version} "
            f"template={ctx.template} "
            f"generated_at={ctx.generated_at.isoformat()}"
        )
        p = document.add_paragraph()
        run = p.add_run(marker_text)
        run.font.size = Pt(1)
        run.font.color.rgb = RGBColor(0xFF, 0xFF, 0xFF)  # blanc sur blanc

        log.debug("documents.branding.docx_invisible_marker_applied")
        return True
    except Exception as exc:  # noqa: BLE001 — fail-safe absolu
        log.warning(
            "documents.branding.docx_invisible_marker_failed",
            error=str(exc),
            error_type=type(exc).__name__,
        )
        return False


# ══════════════════════════════════════════════════════════════
# Public API
# ══════════════════════════════════════════════════════════════

__all__ = [
    "BRANDING_VERSION",
    "BRAND_NAME",
    "BRAND_COMPANY",
    "BRAND_TAGLINE",
    "BRAND_WEBSITE",
    "AI_TRANSPARENCY_NOTICE_FR",
    "AI_TRANSPARENCY_NOTICE_EN",
    "INVISIBLE_HTML_MARKER_TEMPLATE",
    "BrandingContext",
    "build_branding_context",
    "generate_intelligent_filename",
    "build_pdf_branding_header_css",
    "build_pdf_branding_footer_css",
    "build_invisible_html_marker",
    "apply_pdf_native_metadata",
    "apply_docx_branding_header",
    "enrich_docx_footer_with_branding",
    "apply_docx_core_properties",
    "apply_docx_invisible_marker",
]
